set -g prefix M-v
set -g escape-time 1

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

set-option -g renumber-windows on

# set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
# set-option -ga terminal-overrides ",*256color*:Tc"
# set -sa terminal-features ",term-256color:RGB"
# set-option -g default-terminal "tmux-256color"
# set-option -ga terminal-features ",term-256color:usstyle"
# set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"

set-option -g status-position top


# My bindings
unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -n M-H previous-window
bind -n M-L next-window

bind -n M-h resize-pane -L 5
bind -n M-l resize-pane -R 5
bind -n M-j resize-pane -D 5
bind -n M-k resize-pane -U 5

# My list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
 

set -g @plugin 'tinted-theming/tinted-tmux'

# Session persistance
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Enable automatic restoring on startup
set -g @@continuum-restore 'on'

# My themes LOL
set -g @tinted-color 'base16-irblack'
# set -g @tinted-color 'base16-harmonic-dark'
# set -g @tinted-color 'base16-dracula'
# set -g @tinted-color 'base16-paraiso'
# set -g @tinted-color 'base16-woodland'
# set -g @tinted-color 'base16-mocha'
# set -g @tinted-color 'base16-marrakesh'
# set -g @tinted-color 'base16-darktooth'
# set -g @tinted-color 'base16-embers'
# set -g @tinted-color 'base16-bespin'
# set -g @tinted-color 'base16-tokyo-night-terminal-dark'
# set -g @tinted-color 'base16-gruvbox-material-dark-hard'

run '~/.config/tmux/plugins/tpm/tpm'
